name: DAST-Scan
permissions:
  issues: write
  contents: write
  packages: write
  security-events: write
  pull-requests: write
  id-token: write
  actions: write

on:
  push:
    branches: [ "main" ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-vuln-app .

      - name: Run container in background
        run: docker run -d -p 127.0.0.1:5000:5000 --name vuln_container python-vuln-app

      - name: Wait for container
        run: sleep 10

      #- name: Authenticate with Docker Hub
      #  run: echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:5000'
          docker_name: "zaproxy/zap-stable"

      - name: Stop container
        if: always()
        run: docker stop vuln_container && docker rm vuln_container

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: zap-scan-report
          path: |
            report.html
            report.md
            report.xml
            zap.yaml